### ISSUE TITLE
Unable to parse checkov results.

### ISSUE THREAD

**Issue by thaskell** [bridgecrewio/checkov-jetbrains-ide#108]
After opening a file, checkov attempts to scan it and then fails. Logs show the following:
```
java.lang.Exception: couldn't parse checkov results output, reason:
{
    "passed": 0,
    "failed": 0,
    "skipped": 0,
    "parsing_errors": 0,
    "resource_count": 0,
    "checkov_version": "2.0.1075"
}

	at com.bridgecrew.CheckovResultKt.getFailedChecksFromResultString(CheckovResult.kt:54)
	at com.bridgecrew.services.CheckovScanService.getGroupedResults(CheckovScanService.kt:138)
	at com.bridgecrew.services.CheckovScanService.analyzeScan(CheckovScanService.kt:110)
	at com.bridgecrew.services.CheckovScanService.access$analyzeScan(CheckovScanService.kt:40)
	at com.bridgecrew.services.CheckovScanService$ScanTask.run(CheckovScanService.kt:165)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:436)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:120)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:496)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I was able to successfully execute the same command as the plugin which showed the same json output as shown in the exception.

If I scan a file with a resource that triggers checks I was consistently getting timeouts through the plugin even though the checkov command with the same arguments would return within 20 seconds.

IntelliJ 2021.3.3:
```
Runtime version: 11.0.14.1+1-b1751.46 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
```
MacOS 12.3.1
Checkov plugin version: 0.0.18
Python version: 3.9.12
Checkov version: 2.0.1075

**Comment by orhovy** [comment]
Thanks for opening the ticket.
This was fixed in version 0.0.19 :)
